### ISSUE TITLE
Feature wanted

### ISSUE THREAD

**Issue by ArvinZhuang** [texttron/tevatron#6]
It would be good to have validation during training.

I understand this might be hard for dense retrievers as encoding collection is expansive.
But I guess we can do something like use DR to rerank top-k docs for a subset of dev queries? I think the reranking score is quite correlated with retrieval scores?

**Comment by luyug** [comment]
One thing we could potentially do is to implement the DPR validation: with a small set of queries, create a pool consisting of their top ranked passages and retrieve from this pool. This result will be a strictly better estimation than reranking. Question is whether we should do this within the train loop or outside it, i.e. just use the encode/retriever scripts. I guess at the end of the day we could put in a switch.

I mentioned PR because I want more people to get involved so that maybe one day we can have a small community.. I could also get back to implement this myself after finishing the JAX interfaces, possibly towards the end of the month.

**Comment by ArvinZhuang** [comment]
yep, make sense to me.

**Comment by luyug** [comment]
oh, btw, we have a `tevatron.utils` namespace. You are more than welcome to put a filtering script there!
