### ISSUE TITLE
How do you get wikipedia-nq?

### ISSUE THREAD

**Issue by ShiyuNee** [texttron/tevatron#90]
The count of samples in wikipedia-nq is 3000+ while the count in original nq dataset is nearly 8000. 

I would like to know how the data is screened.

Thanks!

**Comment by ShiyuNee** [comment]
> The count of samples in wikipedia-nq is 3000+ while the count in original nq dataset is nearly 8000.
> 
> I would like to know how the data is screened.
> 
> Thanks!

I got the answer in the paper of DPR.

**Comment by MXueguang** [comment]
sorry for not replying in time.

just to have a record:
The training data for wikipedia-nq is converted from the original DPR repo.
The difference from original NQ is due to:
<img width="526" alt="Screen Shot 2023-10-22 at 3 44 18 PM" src="https://github.com/texttron/tevatron/assets/34487581/718cc0e1-7297-4f47-84da-03d899bb39dd">

**Comment by ShiyuNee** [comment]
> sorry for not replying in time.
> 
> just to have a record: The training data for wikipedia-nq is converted from the original DPR repo. The difference from original NQ is due to: <img alt="Screen Shot 2023-10-22 at 3 44 18 PM" width="526" src="https://user-images.githubusercontent.com/34487581/277188695-718cc0e1-7297-4f47-84da-03d899bb39dd.png">

Thanks.
